version: '3.8'

services:
  # Aplicação Next.js principal (única instância)
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs-mf
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=http://json-server:3001
    depends_on:
      - json-server
    networks:
      - mf-network
    # Não expor porta externa - apenas para containers internos

  # Micro-frontend 1: Home (Nginx Proxy)
  mf-home:
    image: nginx:alpine
    ports:
      - "9001:80"
    volumes:
      - ./nginx/home.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - mf-network
    restart: unless-stopped

  # Micro-frontend 2: Analytics (Nginx Proxy)
  mf-analytics:
    image: nginx:alpine
    ports:
      - "9002:80"
    volumes:
      - ./nginx/analytics.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - mf-network
    restart: unless-stopped

  # Micro-frontend 3: Transactions (Nginx Proxy)
  mf-transactions:
    image: nginx:alpine
    ports:
      - "9003:80"
    volumes:
      - ./nginx/transactions.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - mf-network
    restart: unless-stopped

  # Single-SPA Shell Orchestrator
  single-spa-shell:
    build:
      context: ./single-spa-shell
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - mf-network
    restart: unless-stopped

  # Shared JSON Server API
  json-server:
    image: node:18-alpine
    container_name: frontend-tech-challenge-api
    working_dir: /app
    volumes:
      - ./db:/app/db
      - ./scripts:/app/scripts
      - ./package.json:/app/package.json
    command: >
      sh -c "
        npm install -g json-server &&
        node scripts/initServerJson.js &&
        json-server --watch db/server.json --port 3001 --host 0.0.0.0
      "
    ports:
      - "3001:3001"
    networks:
      - mf-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/transactions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mf-network:
    driver: bridge
